development:
    adapter: postgresql
    host: localhost
    database: wecrowd
    username: wecrowd
    password: wecrowd
    pool: 5
    timeout: 5000
    
stage:
    adapter: postgresql
    host: localhost
    database: wecrowd
    username: wecrowd
    password: <%= ENV['WECROWD_DATABASE_PASSWORD'] %>
    pool: 5
    timeout: 5000
    
production:
    adapter: postgresql
    host: localhost
    database: wecrowd
    username: wecrowd
    password: <%= ENV['WECROWD_DATABASE_PASSWORD'] %>
    pool: 5
    timeout: 5000