development:
  client_id: <%= ENV['WECROWD_CLIENT_ID'] %>
  client_secret: <%= ENV['WECROWD_CLIENT_SECRET'] %>
  account_id: <%= ENV['WECROWD_ACCOUNT_ID'] %>
  access_token: <%= ENV['WECROWD_ACCESS_TOKEN'] %>    
stage:
    client_id: <%= ENV['WECROWD_CLIENT_ID'] %>
    client_secret: <%= ENV['WECROWD_CLIENT_SECRET'] %>
    account_id: <%= ENV['WECROWD_ACCOUNT_ID'] %>
    access_token: <%= ENV['WECROWD_ACCESS_TOKEN'] %>
      
production:
    client_id: <%= ENV['WECROWD_CLIENT_ID'] %>
    client_secret: <%= ENV['WECROWD_CLIENT_SECRET'] %>
    account_id: <%= ENV['WECROWD_ACCOUNT_ID'] %>
    access_token: <%= ENV['WECROWD_ACCESS_TOKEN'] %>